import Head from 'next/head'
import {Header, Banner, Locations, CardData, LargeCard} from '../shared/components'
import {MainLayout} from '../shared/layouts'
export default function Home({explerData, cardData}) {
  return (
    <div>
      <Head>
        <title>Airbn App Clone</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
         <Header />
         <Banner />
         <main className="max-w-7xl mx-auto px-8 sm:px-16">
              <Locations explerData={explerData}/>
              <CardData cardData={cardData}/>
              <LargeCard 
                  img="https://links.papareact.com/4cj"
                  title="Las grandes ciudades"
                  description="A un solo click"
                  buttonText="Inspirate"
              />
        </main>
      </MainLayout>
    </div>
  )
}

export async function getStaticProps() {
  const explerData = await fetch('https://links.papareact.com/pyp')
  .then((res)=> res.json());

  const cardData =  await fetch('https://links.papareact.com/zp1')
  .then((res) => res.json());
  
  return {
    props:{
      explerData,
      cardData
    }
  }
}

